Kalina Task1
cscenter/hpcourse pull request #225
Opened 2019-03-31 22:03 UTC by AlexeyKalina

2019-04-07 18:41 UTC, jatvarthur requested changes

2019-04-07 18:41 UTC, jatvarthur commented on csc/2019/1.Pthread/KalinaAI/producer_consumer.cpp
> +#include <pthread.h>
На моих тестовых данных программа завершается, но не выдает результат
```
jatvarthur@userver:~/cscenter/problem1_pthreads$ ./lab.a 5 50 < input1.txt
jatvarthur@userver:~/cscenter/problem1_pthreads$ ./lab.a 5 50 < input1.txt > output.txt
jatvarthur@userver:~/cscenter/problem1_pthreads$ ./lab.a 1 5 < input1.txt
jatvarthur@userver:~/cscenter/problem1_pthreads$ echo $?
179
```

2019-04-07 18:41 UTC, jatvarthur commented on csc/2019/1.Pthread/KalinaAI/producer_consumer.cpp
> +}
Здесь сохраняется указатель на локальную переменную, это очень подозрительно

2019-04-14 20:06 UTC, jatvarthur requested changes

2019-04-14 20:06 UTC, jatvarthur commented on csc/2019/1.Pthread/KalinaAI/producer_consumer.cpp
> +      error_code_ptr = new int();
delete не забыли сделать при выходе из потока?

2019-04-30 07:42 UTC, AlexeyKalina commented on csc/2019/1.Pthread/KalinaAI/producer_consumer.cpp
> +      error_code_ptr = new int();
done

2019-05-03 13:22 UTC, jatvarthur approved these changes

2019-05-12 15:54 UTC, merged