1.Pthread ChausovAG
cscenter/hpcourse pull request #227
Opened 2019-04-03 00:01 UTC by dxahtepb

2019-04-07 19:49 UTC, jatvarthur requested changes

2019-04-07 19:49 UTC, jatvarthur commented on csc/2019/1.Pthread/ChausovAG/solution.cpp
> +        return 0;
Почему? Внимательно посмотрите смысл первого параметра в задании. И, раз считаете эту ситуацию ошибочной, то правильно будет вернуть ненулевой код возврата, т.к. скрипты ожидают, что при нулевом коде возврата в stdout будет результат

2019-04-07 19:49 UTC, jatvarthur commented on csc/2019/1.Pthread/ChausovAG/solution.cpp
> +//OWERFLOW is collapsing with OWERFLOW defined in <cmath> (required in <random>)
colliding?

2019-04-07 19:49 UTC, jatvarthur commented on csc/2019/1.Pthread/ChausovAG/solution.cpp
> +        pthread_mutex_lock(&mutex_);
Поскольку Вы тут накапсулировали всего, тут тоже можно использовать RAII и класс типа
`MutexLock lock{&mutex_}`, который в конструкторе будет делать lock, а в деструкторе unlock :)

2019-04-07 19:49 UTC, jatvarthur commented on csc/2019/1.Pthread/ChausovAG/solution.cpp
> +    MessageQueue<int> link{2};
Почему 2?

2019-04-07 19:49 UTC, jatvarthur commented on csc/2019/1.Pthread/ChausovAG/solution.cpp
> +        link_state = link->get(curr_value);
Правильно ли я понимаю, что у Вас по сути pull-стратегия, то есть консумеры уведомляют поток продючера, что готовы потребить очередное значение? Если очередного значения в очереди нет, то мы тут либо засыпаем на некоторое время, либо крутимся в бесконечном цикле, впустую потребляя такты процессора?
Правильнее (и по заданию) реализовать обратную стратегию, когда консумер всегда блокируется тут, пока не будет либо значения, либо завершения продюсера (т.е. мы не получаем `LinkState::EMPTY`, его можно использовать если Вы решите сделать неблокирующий вызов наподобие `peek()`), о чем должен сигнализировать продюсер

2019-04-07 21:33 UTC, dxahtepb commented on csc/2019/1.Pthread/ChausovAG/solution.cpp
> +        return 0;
Действительно, неправильно прочитал условие в этом месте. Буду возвращать какой-нибудь код ошибки, отличный от 0 или 1.

2019-04-07 21:33 UTC, dxahtepb commented on csc/2019/1.Pthread/ChausovAG/solution.cpp
> +//OWERFLOW is collapsing with OWERFLOW defined in <cmath> (required in <random>)
Names collision, да)

2019-04-07 21:34 UTC, dxahtepb commented on csc/2019/1.Pthread/ChausovAG/solution.cpp
> +    MessageQueue<int> link{2};
Магическое чилсло, надо бы константу завести.

2019-04-07 21:38 UTC, dxahtepb commented on csc/2019/1.Pthread/ChausovAG/solution.cpp
> +        link_state = link->get(curr_value);
Да, всё работает приблизительно так. Сделаю операцию получения значения блокирующей. При этом put останется также блокирующим при заполненной очереди, если я правильно понял.

2019-04-07 22:55 UTC, dxahtepb commented on csc/2019/1.Pthread/ChausovAG/solution.cpp
> +        link_state = link->get(curr_value);
В коде очереди была проблема, что если все консьюмеры "умерли" от переполнения, то продьюсер бы вечно дожидался, что кто-то прочитает его сообщения.

2019-04-14 19:47 UTC, jatvarthur approved these changes

2019-05-12 15:56 UTC, merged