[HW 1. Pthread API] Егор Намаконов, СПбГУ
cscenter/hpcourse pull request #228
Opened 2019-04-06 20:38 UTC by fresheed

2019-04-10 19:45 UTC, jatvarthur requested changes

2019-04-10 19:45 UTC, jatvarthur commented on csc/2019/1.Pthread/NamakonovES/pc.cpp
> +int *noerrorPtr=&noerrorValue, *overflowPtr=&overflowValue;
мне не очень нравится вот эта идея с глобальными указателями, а если у вас будет 150 разных кодов ошибок? Правильнее будет для каждого потока выделять память под хранения int и записывать код возврата в него. При завершении потока память необходимо будет освобождать.

2019-04-10 19:45 UTC, jatvarthur commented on csc/2019/1.Pthread/NamakonovES/pc.cpp
> +  // cout << msg << endl;
никогда не передавайте строки по значению (или на это должны быть очень веские причины), т.к. здесь выполняется ненужное копирования и уничтожение данных, с большими строками это очень сильно влияет на производительность. Пользуйтесь либо const ref, либо r-value ref

2019-04-10 19:45 UTC, jatvarthur commented on csc/2019/1.Pthread/NamakonovES/pc.cpp
> +using namespace std;
в общем случае плохая практика, здесь менять не надо, просто имейте в виду.

2019-04-10 19:45 UTC, jatvarthur commented on csc/2019/1.Pthread/NamakonovES/pc.cpp
> +  //this_thread::sleep_for(chrono::seconds(3));
вместо комментариев поможет в таких ситуациях #define

2019-04-10 19:55 UTC, jatvarthur commented on csc/2019/1.Pthread/NamakonovES/pc.cpp
> +  getline(cin, rawInput);
почему не хотите читать напрямую из cin? зачем копировать мегабайты данных?

2019-04-14 08:44 UTC, fresheed commented on csc/2019/1.Pthread/NamakonovES/pc.cpp
> +int *noerrorPtr=&noerrorValue, *overflowPtr=&overflowValue;
Если честно, непонятно, зачем здесь использовать TLS. Раз мы всё равно передаём в тред указатель на структуру, в которую будем складывать результат, можно работать с ним напрямую, а не оборачивать в get/setspecific.

2019-04-14 08:49 UTC, fresheed commented
Сделал изменения согласно запрошенным правкам.

2019-04-14 20:08 UTC, jatvarthur commented on csc/2019/1.Pthread/NamakonovES/pc.cpp
> +int *noerrorPtr=&noerrorValue, *overflowPtr=&overflowValue;
согласен, это скорее в учебных целях, однако на большинстве реальных систем функционал типа last error делается именно так

2019-04-14 20:16 UTC, jatvarthur approved these changes

2019-05-11 22:06 UTC, closed without merging