Lab 1 is done.
cscenter/hpcourse pull request #229
Opened 2019-04-07 18:40 UTC by GoncharovArtyom

2019-04-10 20:01 UTC, jatvarthur requested changes

2019-04-10 20:01 UTC, jatvarthur commented on csc/2019/1.Pthread/GoncharovAV/main.cpp
> +using namespace std;
в общем случае плохая практика, здесь менять не надо, просто имейте в виду.

2019-04-10 20:01 UTC, jatvarthur commented on csc/2019/1.Pthread/GoncharovAV/main.cpp
> +    auto code_p = new int(code);
обязательно ли перевыделять память? почему бы не использовать существующую?

2019-04-10 20:01 UTC, jatvarthur commented on csc/2019/1.Pthread/GoncharovAV/main.cpp
> +    getline(cin, input);
почему не хотите читать напрямую из cin? зачем копировать мегабайты данных?

2019-04-10 20:01 UTC, jatvarthur commented on csc/2019/1.Pthread/GoncharovAV/main.cpp
> +    stringstream input = get_input_stream();
кстати, не проверяли как копируются stringstream? вызываются ли тут конструкторы копирования (или другие) и что они делают?

2019-04-10 20:01 UTC, jatvarthur commented on csc/2019/1.Pthread/GoncharovAV/main.cpp
> +        sum += result->sum;
может ли здесь возникнуть переполнение?

2019-04-20 10:34 UTC, GoncharovArtyom commented on csc/2019/1.Pthread/GoncharovAV/main.cpp
> +    auto code_p = new int(code);
Поправил.

2019-04-20 10:35 UTC, GoncharovArtyom commented on csc/2019/1.Pthread/GoncharovAV/main.cpp
> +    getline(cin, input);
Тоже поправил.

2019-04-20 10:40 UTC, GoncharovArtyom commented on csc/2019/1.Pthread/GoncharovAV/main.cpp
> +    stringstream input = get_input_stream();
Совсем это удалил :) На [stackoverflow](https://stackoverflow.com/questions/3442520/how-copy-from-one-stringstream-object-to-another-in-c) пишут, что "streams are non-copyable (though they are movable)", так что данные не должны лишний раз копироваться.

2019-04-20 10:40 UTC, GoncharovArtyom commented on csc/2019/1.Pthread/GoncharovAV/main.cpp
> +        sum += result->sum;
Добавил условие с проверкой.

2019-04-26 03:38 UTC, jatvarthur requested changes
на тесте
```
+ ./lab.a 25 1
./run.sh: line 11: 20129 Segmentation fault      (core dumped) ./lab.a 25 1 < input1.txt
```

2019-04-28 12:56 UTC, GoncharovArtyom commented
Поправил несколько ошибок.

2019-04-29 04:51 UTC, jatvarthur requested changes
все еще падает
```
+ ./lab.a 23 5
./run.sh: line 9: 10064 Segmentation fault      (core dumped) ./lab.a 23 5 < input1.txt

```

2019-04-30 02:08 UTC, jatvarthur approved these changes

2019-05-12 15:54 UTC, merged