1 task
cscenter/hpcourse pull request #230
Opened 2019-04-09 01:34 UTC by vmishenev

2019-04-11 13:56 UTC, jatvarthur requested changes

2019-04-11 13:56 UTC, jatvarthur commented on csc/2019/1.Pthread/MishenevVS/pc.cpp
> +        consumer_started.trigger(); // signal to producer and interruptor
зачем это делать в цикле?

2019-04-11 13:56 UTC, jatvarthur commented on csc/2019/1.Pthread/MishenevVS/pc.cpp
> +    return sum > INT32_MAX - d;
если d < 0?

2019-04-11 13:56 UTC, jatvarthur commented on csc/2019/1.Pthread/MishenevVS/pc.cpp
> +            active_consumers--; // is protected by shared_data_mtx
почему защищено? я вижу, что мьютекс освобождается строчкой выше

2019-04-11 13:58 UTC, jatvarthur commented on csc/2019/1.Pthread/MishenevVS/pc.cpp
> +    int *shared_data = reinterpret_cast<int *>(arg);
почему используете reinterpret_cast?

2019-04-11 20:42 UTC, vmishenev commented on csc/2019/1.Pthread/MishenevVS/pc.cpp
> +            active_consumers--; // is protected by shared_data_mtx
местами строчки переставил)

2019-04-11 20:43 UTC, vmishenev commented
исправлено

2019-04-14 19:51 UTC, jatvarthur approved these changes

2019-05-12 15:56 UTC, merged