pthread lab
cscenter/hpcourse pull request #231
Opened 2019-04-10 22:35 UTC by dm-kovalev

2019-04-14 19:19 UTC, jatvarthur approved these changes
Глаз ни за что не зацепился, единственное using namespace std; не приветствуется, но здесь допустимо. ОК.

2019-04-14 19:25 UTC, jatvarthur requested changes

2019-04-14 19:25 UTC, jatvarthur commented on csc/2019/1.Pthread/KovalevDA/main.cpp
> +        if (result->error == OVERFLOW || checked_add(sum, result->partial_sum, &sum)) {
Но, вот здесь вы делаете malloc(), но free() я не вижу

2019-04-14 20:25 UTC, dm-kovalev commented on csc/2019/1.Pthread/KovalevDA/main.cpp
> +        if (result->error == OVERFLOW || checked_add(sum, result->partial_sum, &sum)) {
Добавил `delete`

2019-05-12 05:39 UTC, jatvarthur approved these changes

2019-05-12 15:50 UTC, merged