hw 1
cscenter/hpcourse pull request #232
Opened 2019-04-12 15:32 UTC by artesby

2019-04-14 19:36 UTC, jatvarthur requested changes

2019-04-14 19:36 UTC, jatvarthur commented on csc/2019/1.Pthread/TimofeevAI/main.cpp
> +                pthread_exit(&consumer_output);
вы передаете указатель на thread local в другой thread, да еще и после завершения треда-владельца Насколько вы уверены, что эта память не будет испорчена?

2019-04-14 19:36 UTC, jatvarthur commented on csc/2019/1.Pthread/TimofeevAI/main.cpp
> +        }
не очень чистый выход получается? остальные треды могли не завершиться, объекты не уничтожили. Большинство систем закроет все само, но все-таки

2019-04-15 11:58 UTC, artesby commented on csc/2019/1.Pthread/TimofeevAI/main.cpp
> +        }
поправил

2019-04-15 12:05 UTC, jatvarthur requested changes

2019-04-15 12:05 UTC, jatvarthur commented on csc/2019/1.Pthread/TimofeevAI/main.cpp
> +        sum += out->local_sum;
delete не забыли для output?

2019-04-15 12:46 UTC, artesby commented on csc/2019/1.Pthread/TimofeevAI/main.cpp
> +        sum += out->local_sum;
он в цикле создается, разве не удаляется сам? добавил

2019-05-12 05:37 UTC, jatvarthur approved these changes

2019-05-12 15:51 UTC, merged