Toshchev KA
cscenter/hpcourse pull request #235
Opened 2019-04-15 12:29 UTC by pragmaspark

В linux (5.0.7-arch1-1-ARCH) при вызове pthread_cancel выходит core dump. Я устал с этим бороться, поэтому сдаю как есть.

2019-04-15 18:24 UTC, jatvarthur commented
```
[II]:   create Consumer 24
[VV]: create threads producer, N consumer and interruptor
./run.sh: line 11:  5013 Segmentation fault      (core dumped) ./lab.a 25 1 < input1.txt
```
у меня тоже падает, проблема практически 100% в вашем коде

2019-04-15 18:40 UTC, jatvarthur requested changes

2019-04-15 18:40 UTC, jatvarthur commented on csc/2019/1.Pthread/ToshchevKA/main.cpp
> +    CHECK_ERROR(pthread_create(&interruptor, NULL, consumer_interruptor_routine, (void *) &consumer), "create Interruptor");
внутренний голос мне подсказывает, что проблема в этой строке

2019-04-15 18:40 UTC, jatvarthur commented on csc/2019/1.Pthread/ToshchevKA/main.cpp
> +    LOG("create threads producer, N consumer and interruptor", 0);
уберите пожалуйста в комиченной версии отладочный лог с консоли, проверять невозможно иначе, можете для этого использовать типа #ifdef DEBUG

2019-04-15 18:40 UTC, jatvarthur commented on csc/2019/1.Pthread/ToshchevKA/main.cpp
> +    }
тут вроде еще надо было спать?

2019-04-15 18:40 UTC, jatvarthur commented on csc/2019/1.Pthread/ToshchevKA/main.cpp
> +    pthread_mutex_unlock(&mutex);
это очень сурово, в если входной поток сотня другая мегабайт?

2019-04-15 18:40 UTC, jatvarthur commented on csc/2019/1.Pthread/ToshchevKA/main.cpp
> +    pthread_setspecific(err, &code);
здесь подозрительно, указатель на что вы сохраняете?

2019-04-15 19:40 UTC, pragmaspark commented on csc/2019/1.Pthread/ToshchevKA/main.cpp
> +    pthread_mutex_unlock(&mutex);
переписал через while

2019-04-15 19:43 UTC, pragmaspark commented on csc/2019/1.Pthread/ToshchevKA/main.cpp
> +    }
Вроде спим только в consumer_routine

В задании:
Задача потока-interruptor проста: пока происходит процесс обновления значений, он должен постоянно пытаться остановить случайный поток consumer (вычисление случайного потока происходит перед каждой попыткой остановки). Как только поток producer произвел последнее обновление, этот поток завершается.

2019-04-15 19:50 UTC, pragmaspark commented on csc/2019/1.Pthread/ToshchevKA/main.cpp
> +    LOG("create threads producer, N consumer and interruptor", 0);
убрал логирование

2019-05-12 05:28 UTC, jatvarthur requested changes

2019-05-12 05:28 UTC, jatvarthur commented on csc/2019/1.Pthread/ToshchevKA/main.cpp
> +#include <pthread.h>
программа все еще падает
```
+ ./lab.a 3 5
./run.sh: line 6:  5130 Segmentation fault      (core dumped) ./lab.a 3 5 < input1.txt
```

2019-12-17 14:45 UTC, closed without merging