solve hw1
cscenter/hpcourse pull request #238
Opened 2019-04-15 19:04 UTC by AndrewP-23

2019-04-15 19:29 UTC, jatvarthur requested changes

2019-04-15 19:29 UTC, jatvarthur commented on csc/2019/1.Pthread/PrudnikovAM/main.cpp
> +#include <pthread.h>
программа не компилируется требуемой строкой, не хватает limist.h, и зависает на тестах

2019-04-15 19:52 UTC, AndrewP-23 commented on csc/2019/1.Pthread/PrudnikovAM/main.cpp
> +#include <pthread.h>
добавил limits.h
странно, у меня компилируется и не зависает на разных прогонах

2019-05-12 05:30 UTC, jatvarthur approved these changes

2019-05-12 15:52 UTC, merged