[HW1] Producer-Consumer, Климов Егор
cscenter/hpcourse pull request #240
Opened 2019-04-15 19:30 UTC by egorklimov

Не знаю к чему тут javadoc'и, наверно привык ;)

2019-04-17 08:31 UTC, jatvarthur commented
и хорошо, что привыкли, для c++ javadoc-и понимают разные инструменты, например, doxygen. Попробуйте, кстати, на досуге обработать им свой исходник

2019-04-17 08:59 UTC, jatvarthur requested changes

2019-04-17 08:59 UTC, jatvarthur commented on csc/2019/1.Pthread/KlimovEG/solution.cpp
> +  if (code == 0 || code == 1)
проверка лишняя, мы же можем добавлять новые коды ошибок, зачем ограничивать?

2019-04-17 08:59 UTC, jatvarthur commented on csc/2019/1.Pthread/KlimovEG/solution.cpp
> +  ConsumerData *data = (ConsumerData *) arg;
сверху static_cast'ом приводите, здесь в стиле C. Лучше все делать однообразно

2019-04-17 08:59 UTC, jatvarthur commented on csc/2019/1.Pthread/KlimovEG/solution.cpp
> +      // failed to create thread.
совсем по-хорошему тут бы надо подчистить уже созданные потоки. И далее по тексту в аналогичных местах

2019-04-27 16:46 UTC, egorklimov commented
Спасибо за совет, попробовал doxygen.
![docs_example](https://user-images.githubusercontent.com/6136993/56852526-2d866680-6925-11e9-86a3-d17a5b8aa9bf.png)

2019-04-27 16:48 UTC, egorklimov commented on csc/2019/1.Pthread/KlimovEG/solution.cpp
> +  if (code == 0 || code == 1)
Исправил: https://github.com/cscenter/hpcourse/pull/240/commits/b9468076f2e33627b37466d2f636de085671e754#diff-71077b8e93bff86da3be7185bf32153aR107

2019-04-27 16:48 UTC, egorklimov commented on csc/2019/1.Pthread/KlimovEG/solution.cpp
> +  ConsumerData *data = (ConsumerData *) arg;
Исправил: https://github.com/cscenter/hpcourse/commit/b9468076f2e33627b37466d2f636de085671e754#diff-71077b8e93bff86da3be7185bf32153aR187

2019-04-27 16:49 UTC, egorklimov commented on csc/2019/1.Pthread/KlimovEG/solution.cpp
> +      // failed to create thread.
Добавил вспомогательную функцию, завершающую потоки: https://github.com/cscenter/hpcourse/pull/240/commits/a236fbb139b1b268479094f4dd15b6b922f69cff#diff-71077b8e93bff86da3be7185bf32153aR255

2019-04-29 07:18 UTC, jatvarthur approved these changes

2019-05-12 15:54 UTC, merged