new home task
cscenter/hpcourse pull request #242
Opened 2019-04-15 19:48 UTC by shparutask

2019-04-17 13:24 UTC, jatvarthur requested changes

2019-04-17 13:24 UTC, jatvarthur commented on csc/2019/1.Pthread/ShparutaSK/main.cpp
> +#define MAX_INT 2147483647
правильней воспользоваться limits.h

2019-04-17 13:24 UTC, jatvarthur commented on csc/2019/1.Pthread/ShparutaSK/main.cpp
> +	while (clock() < time_end);
так делать нельзя. Поток должен переводится в спящее состояние средствами ОС, в этом случае он не будет потреблять ресурсы процессора, и ОС сможет его разбудить досрочно или завершить. В вашем случае поток будет потреблять 100% CPU, крутясь в бесконечном цикле

2019-04-17 13:24 UTC, jatvarthur commented on csc/2019/1.Pthread/ShparutaSK/main.cpp
> +		c = getchar();
это неправильно. Вы создаете множество объектов синхронизации, по одному на значение. Это не имеет смысла. Должен быть 1 объект синхронизации на группу разделяемых данных. Разделяемые данные - это одно целое число - текущее прочитанное значение. Массив здесь не нужен

2019-04-17 13:24 UTC, jatvarthur commented on csc/2019/1.Pthread/ShparutaSK/main.cpp
> +	}
Кроме того, getchar() тут тоже не нужен, достаточно читать только числа. Читать их нужно, пока не будет достигнут конец файла.

2019-04-17 13:24 UTC, jatvarthur commented on csc/2019/1.Pthread/ShparutaSK/main.cpp
> +	}
смысл этого цикла?

2019-04-17 13:24 UTC, jatvarthur commented on csc/2019/1.Pthread/ShparutaSK/main.cpp
> +		if (!sharedata_thread[i].was_consumed)
Этот цикл поправите в соответствии с producer

2019-04-17 13:24 UTC, jatvarthur commented on csc/2019/1.Pthread/ShparutaSK/main.cpp
> +	pthread_cancel(*(pthread_t *)arg);
это надо делать в цикле, пока есть еще живые потоки consumer

2019-04-17 13:24 UTC, jatvarthur commented on csc/2019/1.Pthread/ShparutaSK/main.cpp
> +	cin >> N;
Обратите внимание, эти параметры передаются через командную строку, а не читаются из ввода.

2019-04-17 13:24 UTC, jatvarthur commented on csc/2019/1.Pthread/ShparutaSK/main.cpp
> +
И точно не надо никаких задержек

2019-04-17 13:24 UTC, jatvarthur commented on csc/2019/1.Pthread/ShparutaSK/main.cpp
> +
Складывать частичные суммы до результата надо здесь

2019-04-17 19:31 UTC, shparutask commented on csc/2019/1.Pthread/ShparutaSK/main.cpp
> +	while (clock() < time_end);
Можете подсказать, какая функция для этого подойдет? usleep и Sleep не работают

2019-04-17 19:34 UTC, shparutask commented on csc/2019/1.Pthread/ShparutaSK/main.cpp
> +		c = getchar();
то есть на каждое число - свой поток? Тогда для чего параметр N, если мы считываем до конца файла?

2019-04-17 19:35 UTC, shparutask commented on csc/2019/1.Pthread/ShparutaSK/main.cpp
> +	}
Как узнать, что пришёл конец файла без getchar?

2019-04-17 19:37 UTC, shparutask commented on csc/2019/1.Pthread/ShparutaSK/main.cpp
> +	}
считывание происходит до перевода каретки - в задании указано так

2019-04-17 19:39 UTC, shparutask commented on csc/2019/1.Pthread/ShparutaSK/main.cpp
> +	}
получить на вход список чисел, и по очереди использовать каждое значение из этого списка для обновления переменной разделяемой между потоками - это не следует из задания?

2019-04-18 10:34 UTC, jatvarthur commented on csc/2019/1.Pthread/ShparutaSK/main.cpp
> +	while (clock() < time_end);
Как не работают? какая у вас ОС?

2019-04-18 10:38 UTC, shparutask commented on csc/2019/1.Pthread/ShparutaSK/main.cpp
> +	while (clock() < time_end);
Windows 7

2019-04-18 10:49 UTC, jatvarthur commented on csc/2019/1.Pthread/ShparutaSK/main.cpp
> +	while (clock() < time_end);
Sleep() - это функция из WInAPI, такое использовать нежелательно, т.к. проверка выполняется под Linux (вообще постарайтесь обойтись без windows.h). Она работает для текущего потока. Если у вас засыпает на ней вся программа, значит где-то проблема с синхронизацией, возможно вы спите с захваченным мьютексом, пока прорамма не проснется и не освободит его, другие потоки не могут его захватить. Попробуйте _sleep().

2019-04-18 19:35 UTC, shparutask commented on csc/2019/1.Pthread/ShparutaSK/main.cpp
> +	while (clock() < time_end);
не работает

2019-04-19 08:28 UTC, jatvarthur commented on csc/2019/1.Pthread/ShparutaSK/main.cpp
> +	while (clock() < time_end);
```
#include <chrono>
#include <thread>`
std::this_thread::sleep_for(std::chrono::microseconds(usec));
```

2019-04-19 08:40 UTC, shparutask commented on csc/2019/1.Pthread/ShparutaSK/main.cpp
> +	while (clock() < time_end);
тоже пробовала)

2019-04-19 08:58 UTC, jatvarthur commented on csc/2019/1.Pthread/ShparutaSK/main.cpp
> +	while (clock() < time_end);
и какой результат? А какой у вас компилятор и настройки компиляции?

2019-04-19 09:09 UTC, shparutask commented on csc/2019/1.Pthread/ShparutaSK/main.cpp
> +	while (clock() < time_end);
Так же не распознается команда - компилирую командой из задания, GNU компилятор, если не ошибаюсь.

2019-04-19 09:31 UTC, jatvarthur commented on csc/2019/1.Pthread/ShparutaSK/main.cpp
> +	while (clock() < time_end);
Конечно присылайте

2019-04-19 20:31 UTC, shparutask commented on csc/2019/1.Pthread/ShparutaSK/main.cpp
> +	while (clock() < time_end);
![image](https://user-images.githubusercontent.com/14240284/56442945-27780080-62fb-11e9-9f8b-f30e186a5d83.png)
![image](https://user-images.githubusercontent.com/14240284/56442975-44143880-62fb-11e9-909d-9a602cb50e16.png)

2019-04-19 20:36 UTC, shparutask commented on csc/2019/1.Pthread/ShparutaSK/main.cpp
> +	while (clock() < time_end);
Компилятор GNU win32 Bc version 1.06-2

2019-04-23 07:43 UTC, shparutask commented on csc/2019/1.Pthread/ShparutaSK/main.cpp
> +	while (clock() < time_end);
Корректно сработал Sleep - можете посмотреть новый коммит?

2019-04-26 03:55 UTC, jatvarthur requested changes

2019-04-26 03:55 UTC, jatvarthur commented on csc/2019/1.Pthread/ShparutaSK/main.cpp
> +	N = (int)argv[1];
так вот она в чем проблема) не обратил внимания, вы как строку в число конвертируете? какое число здесь получаете?
и попробуйте убрать Sleep(), верните из C++ вариант, т.к. я проверяю на LInux, и мне не хочется менять ваш исходник

2019-04-26 03:57 UTC, jatvarthur commented on csc/2019/1.Pthread/ShparutaSK/main.cpp
> +	N = (int)argv[1];
а у вас компилятор не ругается?
```
main.cpp: In function ‘int main(int, char**)’:
main.cpp:193:17: error: cast from ‘char*’ to ‘int’ loses precision [-fpermissive]
  N = (int)argv[1];
                 ^
main.cpp:194:43: error: cast from ‘char*’ to ‘int’ loses precision [-fpermissive]
  max_time_milliseconds_sleep = (int)argv[2];
```
это предупреждение не показывает суть проблемы, но сразу должно насторожить

2019-04-26 11:03 UTC, shparutask commented on csc/2019/1.Pthread/ShparutaSK/main.cpp
> +	N = (int)argv[1];
"попробуйте убрать Sleep(), верните из C++ вариант" - можете пояснить, что это значит? Не очень понятно

С преобразованием все работало, предупреждений не было

2019-04-26 11:19 UTC, jatvarthur commented on csc/2019/1.Pthread/ShparutaSK/main.cpp
> +	N = (int)argv[1];
Насчет преобразования посомневаюсь. Запустите программу под отладчиком с параметрами 5 50, поставьте точку останова на начало программы и посмотрите в Watches чему у вас равны N  и max_time_milliseconds_sleep.
Или добавьте после преобразования
```
std::cout << "N=" << N << ", time=" << max_time_milliseconds_to_sleep << std::endl;
```
и запустите c теми же параметрами
```
main.exe 5 50
```
Чему равны N и max_time_?

Верните C++, это тот вариант
```
#include <chrono>
#include <thread>
std::this_thread::sleep_for(std::chrono::microseconds(usec));
```

2019-04-26 11:22 UTC, jatvarthur commented on csc/2019/1.Pthread/ShparutaSK/main.cpp
> +	N = (int)argv[1];
Для C++ includes не забыли сделать, когда у вас была проблема с компиляцией?

2019-04-26 17:52 UTC, shparutask commented on csc/2019/1.Pthread/ShparutaSK/main.cpp
> +	N = (int)argv[1];
исправила преобразование и sleep - новый коммит

2019-04-26 17:53 UTC, shparutask commented on csc/2019/1.Pthread/ShparutaSK/main.cpp
> +	N = (int)argv[1];
Да, один include пропустила)

2019-04-29 04:46 UTC, jatvarthur requested changes
программа падает в 
```
./run.sh: line 11:  6944 Segmentation fault      (core dumped) ./lab.a 25 1 < input1.txt
```
или зависает

2019-05-02 09:51 UTC, shparutask commented
Можете подсказать, как это увидеть и исправить, если у меня программа продолжает не компилироваться с командой sleep_for? У меня ОС Windows 7 и GNU компилятор, в задании не было сказано про то, что нужно ставить Linux.

2019-05-03 13:14 UTC, jatvarthur requested changes

2019-05-03 13:14 UTC, jatvarthur commented on csc/2019/1.Pthread/ShparutaSK/main.cpp
> +#include <windows.h>
Удалите этот заголовок, он вам теперь не нужен

2019-05-03 13:14 UTC, jatvarthur commented on csc/2019/1.Pthread/ShparutaSK/main.cpp
> +#define HAVE_STRUCT_TIMESPEC
Теперь программа падает с
```
+ ./lab.a 3 5
./run.sh: line 6:  2417 Floating point exception(core dumped) ./lab.a 3 5 < input1.txt
+ ./lab.a 7 5
./run.sh: line 7:  2424 Floating point exception(core dumped) ./lab.a 7 5 < input1.txt
```
вы как программу тестируете? Правильный ли ответ получаете на тестовых данных? сделайте файл с несколькими тысячами чисел.
Ошибка вот такая, возможно есть проблема с делением ```actual_consumers_count```
```
traps: lab.a[2627] trap divide error ip:561b49b8b284 sp:7f2a473e1ee0 error:0 in lab.a[561b49b8a000+4000]
```

2019-05-03 13:14 UTC, jatvarthur commented on csc/2019/1.Pthread/ShparutaSK/main.cpp
> +	while (!consumer_started);
так делать не надо, никаких пустых циклов. тут нужна синхронизация, или на худой случай sleep

2019-05-03 13:14 UTC, jatvarthur commented on csc/2019/1.Pthread/ShparutaSK/main.cpp
> +		while (!consumer_procceed);
аналогично, никаких пустых циклов. Посмотрите на вызов ```pthread_cond_wait()```

2019-05-03 13:14 UTC, jatvarthur commented on csc/2019/1.Pthread/ShparutaSK/main.cpp
> +		while (!data_read && producer_running);
аналогично

2019-05-03 13:14 UTC, jatvarthur commented on csc/2019/1.Pthread/ShparutaSK/main.cpp
> +			consumer_procceed = true;
посмотрите на вызов ```pthread_cond_signal()```

2019-05-03 13:14 UTC, jatvarthur commented on csc/2019/1.Pthread/ShparutaSK/main.cpp
> +		pthread_cancel(consumers[(1 + rand() % actual_consumers_count) - 1]);
Подумайте, не может ли тут ```actual_consumers_count``` равно нулю, например, при стопе consumers.

2019-05-12 05:18 UTC, jatvarthur requested changes

2019-05-12 05:18 UTC, jatvarthur commented on csc/2019/1.Pthread/ShparutaSK/main.cpp
> +		pthread_cond_wait(&consumer_started_cond, &mutex_common);
посмотрите внимательно на использование мьютекса в ```pthread_cond_wait()```, все ли здесь правильно?

2019-05-12 05:18 UTC, jatvarthur commented on csc/2019/1.Pthread/ShparutaSK/main.cpp
> +			std::this_thread::sleep_for(std::chrono::microseconds(max_time_milliseconds_sleep));
время для засыпания должно выбираться случайным образом, уточните по заданию

2019-05-12 05:18 UTC, jatvarthur commented on csc/2019/1.Pthread/ShparutaSK/main.cpp
> +			break;
не нужно и здесь добавить синхронизацию для ```producer_running``` и ```data_read```

2019-05-12 05:18 UTC, jatvarthur commented on csc/2019/1.Pthread/ShparutaSK/main.cpp
> +			std::this_thread::sleep_for(std::chrono::microseconds(max_time_milliseconds_sleep));
и сейчас программа очень долго работает, возможно зависает, возможно я не дождался результата из-за долгого времени сна. Попробуйте на 4000-5000 числах во входном потоке проверить

2019-05-13 05:03 UTC, jatvarthur approved these changes
grats

2019-05-13 05:03 UTC, merged