HW1: pthread API
cscenter/hpcourse pull request #244
Opened 2019-04-15 20:45 UTC by ARostovsky

2019-04-17 13:12 UTC, jatvarthur requested changes

2019-04-17 13:12 UTC, jatvarthur commented on csc/2019/1.Pthread/RostovskyAA/main.cpp
> +        data = argument;
почему здесь запись не синхронизирована? И здесь вы обращаетесь к глобальной переменной, а в consumer передаете ее как параметр в поток, не принципиально, но желательно однообразие

2019-04-17 13:12 UTC, jatvarthur commented on csc/2019/1.Pthread/RostovskyAA/main.cpp
> +}
как работает thread local? как нужно возвращать код ошибки из потока?

2019-04-17 13:12 UTC, jatvarthur commented on csc/2019/1.Pthread/RostovskyAA/main.cpp
> +        pthread_mutex_lock(&threadsMutex);
Нужна ли здесь синронизация? Что она делает?

2019-04-17 13:12 UTC, jatvarthur commented on csc/2019/1.Pthread/RostovskyAA/main.cpp
> +        sum += *result;
Тут тоже может быть переполнение

2019-04-17 13:12 UTC, jatvarthur commented on csc/2019/1.Pthread/RostovskyAA/main.cpp
> +    std::cin >> consumersCount;
Обратите внимание, что параметры должны передаваться из командной строки, а не читаться из потока ввода. В потоке ввода только числа для суммирования

2019-04-22 12:26 UTC, ARostovsky commented on csc/2019/1.Pthread/RostovskyAA/main.cpp
> +    std::cin >> consumersCount;
processed

2019-04-22 12:26 UTC, ARostovsky commented on csc/2019/1.Pthread/RostovskyAA/main.cpp
> +        sum += *result;
processed

2019-04-22 12:27 UTC, ARostovsky commented on csc/2019/1.Pthread/RostovskyAA/main.cpp
> +        pthread_mutex_lock(&threadsMutex);
processed

2019-04-22 12:27 UTC, ARostovsky commented on csc/2019/1.Pthread/RostovskyAA/main.cpp
> +        data = argument;
processed

2019-04-22 12:27 UTC, ARostovsky commented on csc/2019/1.Pthread/RostovskyAA/main.cpp
> +}
processed

2019-04-26 03:44 UTC, jatvarthur requested changes

2019-04-26 03:44 UTC, jatvarthur commented on csc/2019/1.Pthread/RostovskyAA/main.cpp
> +            break;
очистили ли данные от оставшихся потоков?

2019-04-26 12:56 UTC, ARostovsky commented on csc/2019/1.Pthread/RostovskyAA/main.cpp
> +            break;
processed

2019-04-29 07:14 UTC, jatvarthur approved these changes

2019-05-12 15:55 UTC, merged