Task2, Логачев Михаил
cscenter/hpcourse pull request #254
Opened 2019-05-15 19:03 UTC by mlogachev

Пока только без итератора :(

2019-05-17 10:38 UTC, jatvarthur requested changes

2019-05-17 10:38 UTC, jatvarthur commented on csc/2019/2.LockFreeSet/MikhailLogachev/src/main/java/ru/compscicenter/mlogachev/LockFreeSetImpl.java
> +        return created.longValue() <= marked_for_deletion.longValue();
насколько это правильно? может ли created или marked поменяться, пока операция не закончена?

2019-05-17 10:38 UTC, jatvarthur commented on csc/2019/2.LockFreeSet/MikhailLogachev/src/main/java/ru/compscicenter/mlogachev/LockFreeSetImpl.java
> +        if (start.next.getReference().val == null) {
можно ли обойтись без этой проверки?

2019-05-17 10:38 UTC, jatvarthur commented on csc/2019/2.LockFreeSet/MikhailLogachev/src/main/java/ru/compscicenter/mlogachev/LockFreeSetImpl.java
> +            if (curr.val.compareTo(value) >= 0) {
а если curr marked, т.е. удален?

2019-05-26 18:22 UTC, mlogachev commented on csc/2019/2.LockFreeSet/MikhailLogachev/src/main/java/ru/compscicenter/mlogachev/LockFreeSetImpl.java
> +        if (start.next.getReference().val == null) {
Упростил код в этом месте

2019-05-26 18:22 UTC, mlogachev commented on csc/2019/2.LockFreeSet/MikhailLogachev/src/main/java/ru/compscicenter/mlogachev/LockFreeSetImpl.java
> +            if (curr.val.compareTo(value) >= 0) {
Рефакторинг по предыдущему комменту эту проблему тоже вроде пофиксили

2019-05-26 18:43 UTC, mlogachev commented on csc/2019/2.LockFreeSet/MikhailLogachev/src/main/java/ru/compscicenter/mlogachev/LockFreeSetImpl.java
> +        return created.longValue() <= marked_for_deletion.longValue();
Переделал метод `isEmpty` на два прохода с проверкой, что между ними не добавилось новых ном

2023-07-14 13:33 UTC, closed without merging